---
packages:
  # devtools
  - { name: git, state: 'latest' }
  - { name: emacs, state: 'latest' }
  - { name: nano, state: 'latest' }
  - { name: gcc, state: 'latest' }
  - { name: jq, state: 'latest' }
  - { name: vlc, state: 'latest' }
  - { name: bash, state: 'latest' }
  - { name: bash-completions, state: 'latest' }
  - { name: docker, state: 'latest' }
  - { name: docker-compose, state: 'latest' }
  # system
  - { name: tree, state: 'latest' }
  - { name: ibus-mozc, state: 'latest' }
  - { name: lsof, state: 'latest' }
  - { name: strace, state: 'latest' }
  - { name: patch, state: 'latest' }
  - { name: htop, state: 'latest' }
  - { name: iftop, state: 'latest' }
  - { name: dstat, state: 'latest' }
  - { name: sysstat, state: 'latest' }
  - { name: iotop, state: 'latest' }
  # devel packages
  - { name: openssl-devel, state: 'latest' }
  - { name: readline-devel, state: 'latest' }
  - { name: zlib-devel, state: 'latest' }
  - { name: libcurl-devel, state: 'latest' }
  - { name: libffi-devel, state: 'latest' }
  - { name: java-1.8.0-openjdk-devel, state: 'latest' }
  # other
  - { name: evince, state: 'latest' }
  - { name: gimp, state: 'latest' }
