---
- name: upgrade all packages
  become: yes
  dnf:
    name: "*"
    state: latest

- name: install the 'Development tools' package group
  become: yes
  dnf:
    name: '@Development tools'
    state: present

- name: base packages
  become: yes
  dnf:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
  with_items: "{{ packages }}"

- name: add atlassian repository
  become: yes
  copy:
    src: atlassian-artifactory.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

- name: install hipchat
  become: yes
  dnf:
    name: hipchat4
    state: latest
    enablerepo: atlassian-artifactory

- name: add Google chrome repo
  become: yes
  copy:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/google-chrome.repo
    owner: root
    group: root
    mode: 0644

- name: install Google chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: latest
    enablerepo: google-chrome

- name: add MySQL repo
  become: yes
  copy:
    src: mysql-community.repo
    dest: /etc/yum.repos.d/mysql-community.repo
    owner: root
    group: root
    mode: 0644

- name: install mysql56-devel
  become: yes
  dnf:
    name: mysql-community-devel
    state: latest
    enablerepo: mysql56-community

- name: install slack
  become: yes
  dnf:
    name: https://downloads.slack-edge.com/linux_releases/slack-2.4.2-0.1.fc21.x86_64.rpm
    state: latest
