---
- name: check if sdkman is installed
  shell: test -d {{ ansible_env.HOME }}/.sdkman && echo "yes" || echo "no"
  register: is_sdkman_installed

- name: install SDKMAN
  shell: curl -s https://get.sdkman.io | bash
  when: is_sdkman_installed.stdout == "no"

- name: install packages
  shell: >
    cd $HOME
    bash -lc "sdk install {{ item }}"
  with_items: "{{ packages }}"
