---
- name: install package(MacOSX)
  become: no
  pip:
    name: "{{ item }}"
    executable: /usr/local/bin/pip
  with_items: "{{ packages }}"
  when: ansible_distribution == 'MacOSX'

- name: install package(Linux)
  become: yes
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip
  with_items: "{{ packages }}"
  when: ansible_distribution != 'MacOSX'

