---
- name: tap external repositories
  become: false
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ repositories }}"

- name: update homebrew
  become: false
  homebrew:
    update_homebrew: yes

- name: install packages
  become: false
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.option | default('') }}"
  with_items: "{{ packages }}"

- name: append login shell
  become: yes
  shell: >
    sh -c "echo '/usr/local/bin/bash' >> /etc/shells"

- name: change login shell
  shell: >
    chsh -s /usr/local/bin/bash
  register: result
  until: result.rc == 0
  retries: 3
