---
- name: check installed elasticsearch
  shell: "yum list installed | grep elasticsearch | grep {{ version }}"
  changed_when: false
  always_run: yes
  ignore_errors: yes
  register: is_es_installed

- name: check elasticsearch-head plugin
  shell: "/usr/share/elasticsearch/bin/plugin list | grep head"
  changed_when: false
  always_run: yes
  ignore_errors: yes
  register: is_es_head_installed
  when: is_es_installed.rc == 0

- name: add elasticsearch-head plugin
  become: yes
  shell: "/usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head"
  when: is_es_installed.rc == 0 and is_es_head_installed.rc != 0
  notify:
    - restart elasticsearch

- name: check kuromoji plugin
  shell: "/usr/share/elasticsearch/bin/plugin list | grep analysis-kuromoji"
  changed_when: false
  always_run: yes
  ignore_errors: yes
  register: is_es_kuromoji_installed
  when: is_es_installed.rc == 0

- name: add kuromoji plugin
  become: yes
  shell: "/usr/share/elasticsearch/bin/plugin install analysis-kuromoji"
  when: is_es_installed.rc == 0 and is_es_kuromoji_installed.rc != 0
  notify:
    - restart elasticsearch
