---
- name: check rbenv.sh
  stat:
    path: /etc/profile.d/rbenv.sh
  register: rbenv_sh
  when: ansible_distribution != 'MacOSX'

- block:
  - name: install rbenv
    become: yes
    git:
      repo: https://github.com/sstephenson/rbenv.git
      dest: "{{ ruby_rbenv_path }}"
  - name: install ruby-build
    become: yes
    git:
      repo: https://github.com/sstephenson/ruby-build.git
      dest: "{{ ruby_rbenv_path }}/plugins/ruby-build"
  - name: rbenv directory
    become: yes
    file:
      dest: "{{ ruby_rbenv_path }}/{{ item }}"
      state: directory
    with_items:
      - shims
      - versions
  - name: rbenv template
    become: yes
    template:
      src: rbenv.sh.j2
      dest: /etc/profile.d/rbenv.sh
      mode: 0775
  when: ansible_distribution != 'MacOSX' and not rbenv_sh.stat.exists
