---
- name: check ruby version
  shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: true
  always_run: true

- name: install ruby
  shell: bash -lc "export MAKE_OPTS=-j2 && rbenv install {{ ruby_version }}"
  when: ruby_installed.rc != 0

- name: rbenv version
  shell: cat {{ ruby_rbenv_path }}/version
  register: ruby_global_version
  changed_when: false
  failed_when: false
  always_run: true

- name: rbenv global
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: ruby_global_version.stdout.find("{{ ruby_version }}") != 0

- name: install ruby gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    executable: /usr/local/rbenv/shims/gem
    state: present
  with_items: "{{ ruby_gems }}"
